### ISSUE TITLE
All 8-bit inc reset N flag, all 8-bit dec set it

### ISSUE THREAD

**Issue by janko-jj** [deeptoaster/opcode-table#11]
Instead of "as defined" all 8-bit `inc` instructions should have "0" for N flag and all `dec` instructions "1" for N flag.

Reference:

In the original Z80 documentation: https://www.zilog.com/docs/z80/um0080.pdf for **INC** page 166:

"N is **reset**."

For **DEC** page 171:

"N is **set**."

**Comment by deeptoaster** [comment]
You're right—I suppose it's not necessarily "as defined" since the manual only describes the N flag's behavior as 0 for `ADD` and 1 for `SUBTRACT`. I'll clarify this.

It might as well just be explicit that `ADD` and `SUBTRACT` respectively reset and set the flag anyway.
