### ISSUE TITLE
Carry flag could be modified by INI/INIR/IND/INDR/OUTI/OTIR/OUTD/OTDR

### ISSUE THREAD

**Issue by sverx** [deeptoaster/opcode-table#12]
Carry flag is NOT _unaffected_ by `INI/INIR/IND/INDR/OUTI/OTIR/OUTD/OTDR`
Wikipedia calls this '[a bug](https://en.wikipedia.org/wiki/Zilog_Z80#Bugs)', check http://z80.info/z80undoc3.txt in the [2.2.6] section to read the details.

**Comment by dt-anchorzero** [comment]
thanks for digging this up—I'll update in the next couple days

**Comment by sverx** [comment]
note that I didn't test this myself
