### ISSUE TITLE
recommend reordering the prefix tables

### ISSUE THREAD

**Issue by fghsgh** [deeptoaster/opcode-table#16]
While the current ordering of the prefix tables (none, CB, DD, DDCB, ED, FD, FDCB) makes the most logical sense (being sorted), it is less practical than the old (pre-Z180) order. I preferred it, because:
- `none` and `ED` are the most irregular, and thereby need to most consultation
- the top of `CB` is also quite irregular
- `DD` reflects `none`, `DDCB` reflects `CB`, so they only very rarely need to be consulted if at all
- `FD` is an exact clone of `DD`, so it is even less important

This made (none, ED, CB, DD, DDCB, FD, FDCB) the most effective layout: the largest amount of instructions could be accessed with the smallest amount of scrolling.

However, an alternative could be to have always-visible links to each of the tables next to the search bar?

**Comment by deeptoaster** [comment]
agreed the order you suggested is more practical—done
