### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by michalin** [deeptoaster/opcode-table#3]
I would like a search function like there was in the last version. For example entering something like "ld a," highlighted all commands that load anything into register a.

**Comment by deeptoaster** [comment]
Thanks for the feedback—I'll see what I can do. For now the best option is to just Ctrl+F—do you prefer the old search bar over it?

**Comment by michalin** [comment]
Yes, this would be perfect.

**Comment by evolutional** [comment]
+1, the old search bar was perfect

**Comment by bhandscomb** [comment]
Indeed the search in the original was so useful... type in add and anything not an add was hidden... Ctrl-F pales in comparison and I would argue not having the search box makes the page/tool less useful.

**Comment by bhandscomb** [comment]
Really ugly hack - grafted in the rehash, hashchange, td each and keyup functions from original HTML, added .bk class to CSS, in just before indexOf(hash) inserted a substring(0,24) call, i.e.
          if ($(this).text().substring(0,24).indexOf(hash) == -1) {
unlike original your mouseover popup is part of the cell content and messes up the old search code... chopping down the cell text sort of works, but probably nowhere near reliable enough - the numbers I chose were complete trial and error...

Must admit I massively prefer the old table... more compact, and the pop-over was easier to read... just my opinion...

**Comment by Cwiiis** [comment]
> Must admit I massively prefer the old table... more compact, and the pop-over was easier to read... just my opinion...

I have to admit, I agree - the filter was why I had this page open, vs just any old reference. It's still very nice and I appreciate the work that's gone into it, but without the filter, it's significantly less useful :(

**Comment by emitdrop** [comment]
+1, the old search bar was what made the page superior to any other

**Comment by deeptoaster** [comment]
Thanks for reminding me to deal with this—the search bar is back now. Sorry it took so long!

The search bar also searches in the description content now. (Helpful if you want to search for "any instruction that changes PC," for example.)
