### ISSUE TITLE
Mouseover bug?

### ISSUE THREAD

**Issue by bhandscomb** [deeptoaster/opcode-table#4]
In new version if you mouse over a row/column heading then move mouse into the table body within that row/column the cell mouseover doesn't trigger the "tooltip" for the cell...

e.g. hover on '7' column heading above rlca, rla etc, then mouse down over rlca, rla, daa... if you mouse out of the column/row within the table body the "correct" table cell highlighting and tooltip behaviour returns.

Original site "worked" as expected, i.e. as you mouse out of the row/column heading onto a table cell the highlight switched to per cell highlighting.

**Comment by deeptoaster** [comment]
Thanks for the report, fixed.
